export const currencies = [
  { label: "Algerian dinar", iso: "DZD" },
  { label: "Australian dollar", iso: "AUD" },
  { label: "Botswana pula", iso: "BWP" },
  { label: "Brazilian real", iso: "BRL" },
  { label: "Brunei dollar", iso: "BND" },
  { label: "Canadian dollar", iso: "CAD" },
  { label: "Chilean peso", iso: "CLP" },
  { label: "Chinese yuan", iso: "CNY" },
  { label: "Czech koruna", iso: "CZK" },
  { label: "Danish krone", iso: "DKK" },
  { label: "Euro", iso: "EUR" },
  { label: "Indian rupee", iso: "INR" },
  { label: "Israeli New Shekel", iso: "ILS" },
  { label: "Japanese yen", iso: "JPY" },
  { label: "Korean won", iso: "KRW" },
  { label: "Kuwaiti dinar", iso: "KWD" },
  { label: "Malaysian ringgit", iso: "MYR" },
  { label: "Mauritian rupee", iso: "MUR" },
  { label: "Mexican peso", iso: "MXN" },
  { label: "New Zealand dollar", iso: "NZD" },
  { label: "Norwegian krone", iso: "NOK" },
  { label: "Omani rial", iso: "OMR" },
  { label: "Peruvian sol", iso: "PEN" },
  { label: "Philippine peso", iso: "PHP" },
  { label: "Polish zloty", iso: "PLN" },
  { label: "Qatari riyal", iso: "QAR" },
  { label: "Russian ruble", iso: "RUB" },
  { label: "Saudi Arabian riyal", iso: "SAR" },
  { label: "Singapore dollar", iso: "SGD" },
  { label: "South African rand", iso: "ZAR" },
  { label: "Swedish krona", iso: "SEK" },
  { label: "Swiss franc", iso: "CHF" },
  { label: "Thai baht", iso: "THB" },
  { label: "Trinidadian dollar", iso: "TTD" },
  { label: "U.A.E. dirham", iso: "AED" },
  { label: "U.K. pound", iso: "GBP" },
  { label: "U.S. dollar", iso: "USD" },
  { label: "Uruguayan peso", iso: "UYU" },
];
